language: cpp

dist: bionic

compiler:
  - gcc

before_install:
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get update -qq
  # - sudo apt install libstdc++-11-dev libstdc++-11-doc

before_script:
  - cd test/data
  - tar -xvf stgtregbz.tar.gz
  - cd ../..
  - mkdir build
  - cd build
  - cmake ..

script:
  - make
  - ./test/unit_tests ../test/data/

matrix:
  include:
    - compiler: gcc
      addons:
        apt:
          sources:
            - sourceline: 'ppa:ubuntu-toolchain-r/test'
          packages:
            - g++-10
      env:
        - CXX=g++-10
        - CC=gcc-10

    - compiler: gcc
      addons:
        apt:
          sources:
            - sourceline: 'ppa:ubuntu-toolchain-r/test'
          packages:
            - g++-11
      env:
        - CXX=g++-11
        - CC=gcc-11

    - compiler: clang
      addons:
        apt:
          sources:
            - sourceline: 'ppa:ubuntu-toolchain-r/test'
            - sourceline: 'deb http://apt.llvm.org/bionic/ llvm-toolchain-bionic-11 main'
              key_url: 'https://apt.llvm.org/llvm-snapshot.gpg.key'
          packages:
            - clang-11
            - g++-10
      env:
        - CXX=clang++-11
        - CC=clang-11

    - compiler: clang
      addons:
        apt:
          sources:
            - sourceline: 'ppa:ubuntu-toolchain-r/test'
            - sourceline: 'deb http://apt.llvm.org/bionic/ llvm-toolchain-bionic-12 main'
              key_url: 'https://apt.llvm.org/llvm-snapshot.gpg.key'
          packages:
            - clang-12
            - g++-10
      env:
        - CXX=clang++-12
        - CC=clang-12

    - compiler: clang
      addons:
        apt:
          sources:
            - sourceline: 'ppa:ubuntu-toolchain-r/test'
            - sourceline: 'deb http://apt.llvm.org/bionic/ llvm-toolchain-bionic-13 main'
              key_url: 'https://apt.llvm.org/llvm-snapshot.gpg.key'
          packages:
            - clang-13
            - g++-10
      env:
        - CXX=clang++-13
        - CC=clang-13
